import { forwardRef } from 'react';
import btsLogo from '/bts-logo.png';
import cambridgeLogo from '/cambridge-logo.png';
import msign from '/msign.png';

interface ReceiptPrintProps {
  data: {
    receiptNumber: string;
    studentName: string;
    studentAdmissionId: string;
    studentPhone: string;
    studentEmail: string;
    programName: string;
    paymentAmount: number;
    paymentMethod: string;
    receiptDate: string;
    generatedBy?: { email: string };
  };
}

const ReceiptPrint = forwardRef<HTMLDivElement, ReceiptPrintProps>(({ data }, ref) => {
  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  };

  const formatTime = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  const formatCurrency = (amount: number) => {
    return amount.toLocaleString('en-US') + ' BDT';
  };

  return (
    <>
      {/* Print-specific styles to hide headers and footers */}
      <style>{`
        @media print {
          @page {
            margin: 10mm 15mm;
            size: A4;
          }
          
          /* Hide browser print header/footer */
          @page {
            margin-top: 0;
            margin-bottom: 0;
          }
          
          body {
            margin: 0;
            padding: 0;
          }
          
          /* Hide URL, date, page numbers */
          .print-header,
          .print-footer,
          .page-number,
          .url,
          .date-time {
            display: none !important;
          }
          
          /* Hide "Generated by" section on print */
          .generated-by {
            display: none !important;
          }
        }
      `}</style>

      <div ref={ref} className="bg-white print:bg-white print:p-0">
        {/* Receipt Container */}
        <div className="p-8 print:p-6 max-w-4xl mx-auto">
          {/* Header with Logos */}
          <div className="flex items-center justify-between border-b border-gray-200 pb-4 mb-4 print:pb-4 print:mb-4">
            <div className="flex items-center gap-4">
              <img src={btsLogo} alt="BTS Logo" className="h-14 w-auto object-contain print:h-12" />
              <div>
                <h1 className="text-2xl font-bold text-gray-900 tracking-tight print:text-xl">Beyond the Syllabus</h1>
                <p className="text-sm text-gray-500 print:text-xs">Cambridge English Training Center</p>
              </div>
            </div>
            <div className="flex items-center gap-3">
              <img src={cambridgeLogo} alt="Cambridge English" className="h-14 w-auto object-contain print:h-12" />
            </div>
          </div>

          {/* Title with Premium Styling */}
          <div className="text-center mb-6 print:mb-4">
            <h2 className="text-3xl font-extrabold text-gray-900 tracking-wider uppercase relative inline-block print:text-2xl">
              Student Admission Receipt
              <span className="absolute -bottom-2 left-0 right-0 h-1 bg-gradient-to-r from-orange-500 via-orange-400 to-orange-500 rounded-full print:h-0.5"></span>
            </h2>
          </div>

          {/* Receipt Info - Subtle Design */}
          <div className="grid grid-cols-2 gap-6 mb-6 print:gap-4 print:mb-4 bg-gradient-to-br from-gray-50 to-gray-100/50 rounded-xl p-5 print:p-3 border border-gray-200 print:border-gray-300">
            <div>
              <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider print:text-[10px]">Receipt Number</p>
              <p className="text-xl font-bold text-gray-900 mt-1 print:text-base">{data.receiptNumber}</p>
            </div>
            <div className="text-right">
              <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider print:text-[10px]">Date & Time</p>
              <p className="text-xl font-bold text-gray-900 mt-1 print:text-base">{formatDate(data.receiptDate)}</p>
              <p className="text-sm text-gray-500 mt-0.5 print:text-xs">{formatTime(data.receiptDate)}</p>
            </div>
          </div>

          {/* Student Information */}
          <div className="mb-5 print:mb-3">
            <h3 className="text-sm font-semibold text-gray-700 uppercase tracking-wider mb-2 flex items-center gap-2 print:text-xs print:mb-1.5">
              <span className="w-1.5 h-5 bg-gradient-to-b from-orange-500 to-orange-600 rounded-full print:h-4"></span>
              Student Information
            </h3>
            <div className="grid grid-cols-2 gap-0 border border-gray-200 rounded-xl overflow-hidden print:border-gray-300">
              <div className="p-3 border-b border-r border-gray-200 bg-gray-50/30 print:p-2 print:text-sm">
                <p className="text-xs text-gray-500 font-medium print:text-[10px]">Student Name</p>
                <p className="font-semibold text-gray-900 text-base mt-0.5 print:text-sm">{data.studentName}</p>
              </div>
              <div className="p-3 border-b border-gray-200 bg-gray-50/30 print:p-2 print:text-sm">
                <p className="text-xs text-gray-500 font-medium print:text-[10px]">Admission ID</p>
                <p className="font-semibold text-gray-900 text-base mt-0.5 print:text-sm">{data.studentAdmissionId}</p>
              </div>
              <div className="p-3 border-r border-gray-200 bg-gray-50/30 print:p-2 print:text-sm">
                <p className="text-xs text-gray-500 font-medium print:text-[10px]">Phone</p>
                <p className="font-semibold text-gray-900 text-base mt-0.5 print:text-sm">{data.studentPhone}</p>
              </div>
              <div className="p-3 bg-gray-50/30 print:p-2 print:text-sm">
                <p className="text-xs text-gray-500 font-medium print:text-[10px]">Email</p>
                <p className="font-semibold text-gray-900 text-base mt-0.5 print:text-sm">{data.studentEmail}</p>
              </div>
            </div>
          </div>

          {/* Program & Payment Information */}
          <div className="mb-6 print:mb-4">
            <h3 className="text-sm font-semibold text-gray-700 uppercase tracking-wider mb-2 flex items-center gap-2 print:text-xs print:mb-1.5">
              <span className="w-1.5 h-5 bg-gradient-to-b from-orange-500 to-orange-600 rounded-full print:h-4"></span>
              Program & Payment Details
            </h3>
            <div className="grid grid-cols-2 gap-4 print:gap-2">
              <div className="border border-gray-200 rounded-xl p-4 bg-gray-50/30 print:p-2 print:border-gray-300">
                <p className="text-xs text-gray-500 font-medium print:text-[10px]">Program Name</p>
                <p className="font-semibold text-gray-900 text-base mt-0.5 print:text-sm">{data.programName}</p>
              </div>
              <div className="border border-gray-200 rounded-xl p-4 bg-gray-50/30 print:p-2 print:border-gray-300">
                <p className="text-xs text-gray-500 font-medium print:text-[10px]">Payment Method</p>
                <p className="font-semibold text-gray-900 text-base mt-0.5 print:text-sm">{data.paymentMethod}</p>
              </div>
              <div className="col-span-2 border-2 border-orange-400 rounded-xl p-4 bg-gradient-to-r from-orange-50 to-orange-100/30 print:p-3 print:border-orange-300">
                <p className="text-xs text-gray-500 font-medium print:text-[10px]">Payment Amount</p>
                <p className="text-3xl font-bold text-orange-600 mt-1 print:text-2xl">{formatCurrency(data.paymentAmount)}</p>
              </div>
            </div>
          </div>

          {/* Signature Section - Admin/Teacher Left, Guardian/Student Right */}
          <div className="mt-6 pt-4 border-t border-gray-200 print:mt-4 print:pt-3">
            <div className="grid grid-cols-2 gap-8 max-w-2xl mx-auto print:gap-6">
              {/* Admin/Teacher Signature - Left */}
              <div className="text-center">
                <div className="h-14 border-b-2 border-gray-400 mb-2 flex items-center justify-center print:h-12">
                  <img 
                    src={msign} 
                    alt="Signature" 
                    className="h-12 w-auto object-contain opacity-80 print:h-10"
                  />
                </div>
                <p className="text-sm font-semibold text-gray-700 print:text-xs">Admin/Teacher Signature</p>
              </div>

              {/* Guardian/Student Signature - Right */}
              <div className="text-center">
                <div className="h-14 border-b-2 border-gray-400 mb-2 flex items-center justify-center print:h-12">
                  <span className="text-sm text-gray-400 italic print:text-xs"></span>
                </div>
                <p className="text-sm font-semibold text-gray-700 print:text-xs">Guardian/Student Signature</p>
              </div>
            </div>
          </div>

          {/* Footer */}
          <div className="mt-6 pt-4 border-t border-gray-200 text-center print:mt-4 print:pt-3">
            <p className="text-sm font-semibold text-gray-700 print:text-xs">
              Thank you for choosing Beyond the Syllabus.
            </p>
            <div className="mt-3 pt-3 border-t border-gray-100 print:mt-2 print:pt-2">
              <p className="text-xs text-gray-400 print:text-[10px]">
                Beyond the Syllabus · Cambridge English Training Center · Dhaka, Bangladesh
              </p>
              <p className="text-xs text-gray-400 mt-1 print:text-[10px] print:mt-0.5">
                www.beyondthesyllabus.org
              </p>
            </div>
          </div>

          {/* Generated By - Hidden on print */}
          <div className="mt-3 text-center generated-by print:hidden">
            <p className="text-[10px] text-gray-300 print:text-[8px]">
              Generated by: {data.generatedBy?.email || 'System'} · {formatDate(data.receiptDate)} {formatTime(data.receiptDate)}
            </p>
          </div>
        </div>
      </div>
    </>
  );
});

ReceiptPrint.displayName = 'ReceiptPrint';

export default ReceiptPrint;