import mongoose, { Schema, Document } from 'mongoose';
import { IReceipt } from '../types/index.js';

export interface IReceiptDocument extends IReceipt, Document {}

const ReceiptSchema = new Schema<IReceiptDocument>(
  {
    receiptNumber: {
      type: String,
      required: [true, 'Receipt number is required'],
      unique: true,
      trim: true,
      index: true,
    },
    studentId: {
      type: Schema.Types.ObjectId,
      ref: 'Student',
      required: [true, 'Student ID is required'],
      index: true,
    },
    studentName: {
      type: String,
      required: [true, 'Student name is required'],
      trim: true,
    },
    studentAdmissionId: {
      type: String,
      required: [true, 'Student admission ID is required'],
      trim: true,
      index: true,
    },
    studentPhone: {
      type: String,
      required: [true, 'Student phone is required'],
      trim: true,
    },
    studentEmail: {
      type: String,
      required: [true, 'Student email is required'],
      trim: true,
      lowercase: true,
    },
    programId: {
      type: Schema.Types.ObjectId,
      ref: 'Program',
      required: [true, 'Program ID is required'],
    },
    programName: {
      type: String,
      required: [true, 'Program name is required'],
      trim: true,
    },
    paymentAmount: {
      type: Number,
      required: [true, 'Payment amount is required'],
      min: [0, 'Payment amount cannot be negative'],
    },
    paymentMethod: {
      type: String,
      enum: ['Cash', 'bKash', 'Nagad', 'Card', 'Bank Transfer'],
      default: 'Cash',
    },
    receiptDate: {
      type: Date,
      default: Date.now,
    },
    generatedBy: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'Generated by is required'],
    },
    isDeleted: {
      type: Boolean,
      default: false,
    },
    deletedAt: {
      type: Date,
      default: null,
    },
  },
  {
    timestamps: true,
  }
);

// Indexes for faster queries
ReceiptSchema.index({ receiptNumber: 1 }, { unique: true });
ReceiptSchema.index({ studentId: 1 });
ReceiptSchema.index({ studentAdmissionId: 1 });
ReceiptSchema.index({ receiptDate: -1 });
ReceiptSchema.index({ paymentAmount: 1 });

export const Receipt = mongoose.model<IReceiptDocument>('Receipt', ReceiptSchema);